# Generated by Django 3.0.5 on 2020-04-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200411_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='planifiado',
            new_name='planificado',
        ),
    ]
