# Generated by Django 3.0.5 on 2020-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200428_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
