# Generated by Django 3.0.5 on 2020-05-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tarea_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes_catalogo'),
        ),
    ]
